project_id = "log-akses"

[functions.log-gate]
verify_jwt = true

[functions.log-card-list]
verify_jwt = true

[functions.card-command]
verify_jwt = true

[functions.command-result]
verify_jwt = true
